name: Rust check

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - '.gitignore'
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SKIP_WASM_BUILD: '1'

    steps:
      - run: sudo apt update && sudo apt install --assume-yes cmake protobuf-compiler
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
      - uses: actions/checkout@v1
      - run: >
          cargo fmt --all -- --check
          && cargo clippy --workspace --tests
          && cargo test --workspace --all-features